# Generated by Django 4.2.4 on 2025-01-14 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "bank_ho_address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "bank_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LokAdalat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lokadalatvenue", models.CharField(max_length=50)),
                ("lokadalatdate", models.DateField()),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banx",
                        to="loka.bank",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userx",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_alpha", models.CharField(max_length=100)),
                ("branch_name", models.CharField(max_length=50)),
                ("branch_addr", models.CharField(max_length=500)),
                ("branch_ifsc", models.CharField(max_length=20)),
                (
                    "bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loka.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionalOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ro_name", models.CharField(max_length=100)),
                ("ro_addr", models.CharField(max_length=500)),
                (
                    "bank_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="loka.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettlementRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_no", models.IntegerField(blank=True)),
                ("cust_name", models.CharField(max_length=50)),
                ("outstanding", models.IntegerField(blank=True)),
                ("totalclosure", models.IntegerField(blank=True)),
                ("compromise_amt", models.IntegerField(blank=True)),
                ("token_money", models.IntegerField(blank=True)),
                ("loan_obj", models.CharField(max_length=20)),
                ("irac", models.CharField(max_length=10)),
                ("pr_waived", models.IntegerField(blank=True)),
                ("int_waived", models.IntegerField(blank=True)),
                ("rest_amount", models.IntegerField(blank=True)),
                ("unapplied_int", models.IntegerField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="loka.profile",
                    ),
                ),
                (
                    "loka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setrow",
                        to="loka.lokadalat",
                    ),
                ),
                (
                    "ro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loka.regionaloffice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="ro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="loka.regionaloffice",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
